## CHANGE this to the name of your plugin.
name: mycooladdon

## CHANGE this to your username.
author: ezcoins

## CHANGE this to a meaninful but short description of your plugin.
description: A new slimefun addon

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.ezcoins.slimefunaddon.MyCoolAddon

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/Slimefun/Addon-Template

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun